### ISSUE TITLE
How to compile nodejs part and Angular interface in single file?

### ISSUE THREAD

**Issue by gerasimvol** [jaredallard/nexe#180]
I compiled my app with nexe. It works fine if exists folder with html file and controllers. Is it possible to compile nodejs + angular frontend part in one file?

**Comment by jaredallard** [comment]
I don't quite understand, do you mean essentially a non bundled app?

**Comment by gerasimvol** [comment]
I mean is it possible to compile angular html template as a part of binary?

**Comment by jaredallard** [comment]
Oh! Just use nexeres. There should be documentation in the README.md on how to utilize embedded files.

Please note it may be broken in the latest release, but I'm working on that today, so have no fear.

**Comment by gerasimvol** [comment]
nexeres? Do you mean include my index.html file in code like:
`resourceFiles: [ './public/index.html', './public/controllers/controller.js' ]`

It doesn't work for me. Still if this files don't exist. Binary doesn't work properly.

**Comment by jaredallard** [comment]
Yup, so it is broken.

**Comment by gerasimvol** [comment]
HI! Did you fix it?

**Comment by jaredallard** [comment]
Sorry, not yet! It should be a simple require change, so not much time, I just need to get to my laptop. Give me a couple hours and it should be done!

**Comment by gerasimvol** [comment]
Sorry for enoying you, but if nexeres are availible now, how can I use it?  If I need `npm install nexeres`, where is documentation about it?

**Comment by gerasimvol** [comment]
Sorry for enoying you, but if nexeres are availible now, how can I use it? If I need npm install nexeres, where is documentation about it?

**Comment by jaredallard** [comment]
Agh! I'm sorry, I've been super busy from my own fault currently. Hopefully Monday I can fix this. (It's a browserify issue regarding .require())

On February 21, 2016 10:14:30 AM PST, Vladimir Gerasimenko <notifications@github.com> wrote:
>Sorry for enoying you, but if nexeres are availible now, how can I use
>it? If I need npm install nexeres, where is documentation about it?
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/jaredallard/nexe/issues/180#issuecomment-186876112

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by jaredallard** [comment]
Hi! `master` branch should fix this! :)

**Comment by enginoid** [comment]
I was experiencing the same issue on 1.1.0 and I can confirm that after switching to master, the exception no longer occurs. Thank you for the fix!

**Comment by gerasimvol** [comment]
I execute `npm install nexeres` and it still doesn't work. How do I switch npm package to master?

**Comment by jaredallard** [comment]
You don't need to npm install nexeres, you need to just `require` it and it will be bundled into your application

**Comment by jaredallard** [comment]
In order to use `master` just pull the git, then `npm link` it.

**Comment by gerasimvol** [comment]
I make 
`git clone https://github.com/jaredallard/nexe.git`
`cd nexe/`
`npm link`

In my main .js file added:
```
var nexeres = require('nexeres');
nexeres.get('./home/vladimir/Desktop/haproxyUI/public/index.html');
nexeres.get('./home/vladimir/Desktop/haproxyUI/public'/controllers/controller.js);
```

but still have error: http://prntscr.com/a7wkin

**Comment by jaredallard** [comment]
First off, I don't think you're utilizing relative directories correctly.

Second of all, have you added the files to combine my specifying them in an resource files array in your `package.json`? (property of the `nexe` object)

**Comment by seansbox** [comment]
The README.md seems to not contain any information regarding the use of nexeres. Just a heads up! Thanks for the great tool!
